name: cktap_protocol
description: A flutter library implementing the Coinkite tap protocol for use with the Satscard and Tapsigner. The plugin is effectively a wrapper around Nunchuk's tap-protocol library.
version: 0.1.0
license: MIT
repository: https://github.com/PeteClubSeven/cktap-protocol-flutter
funding:
  - https://app.mash.com/e/peteclubseven
platforms:
  android:
  ios:

environment:
  sdk: '>=2.19.6 <4.0.0'
  flutter: ">=3.7.12"

dependencies:
  cktap_transport: ^0.1.0
  ffi: '>=2.0.0 <2.1.0' # Requires Flutter 3.10
  flutter:
    sdk: flutter
  plugin_platform_interface: '>=2.1.3 <2.1.7' # Requires Flutter 3.10

dev_dependencies:
  ffigen: <8.0.0 # Requires Flutter 3.10
  flutter_test:
    sdk: flutter
  flutter_lints: <3.0.0 # Requires Flutter 3.10

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
