name: build
on: [push]
jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        flutter: ['3.7.12', '3.16.5', 'any']
        include:
          - os: macos-14      # macOS-latest is x86_64 and macOS 14 is ARM64
            flutter: '3.7.12' # Flutter 3.7.12 is to maintain Breez support
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.channel == 'any' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ matrix.flutter }}

      - if: matrix.os == 'macos-12' || matrix.os == 'macos-latest'
        name: Install dependencies (macOS 12)
        run: brew install coreutils

      - name: Set up Flutter
        run: |
          flutter config --no-analytics
          flutter doctor -v
          flutter pub get

      - if: startsWith(matrix.os, 'macos')
        name: Build iOS frameworks
        run: |
          cd example
          flutter build ios-framework

      - if: startsWith(matrix.os, 'macos')
        name: Build iOS example
        run: |
          cd example
          flutter build ios --no-codesign

      - name: Build Android plugin
        run: |
          flutter build aar

      - name: Build Android example
        run: |
          cd example
          flutter build apk --debug
          flutter build apk --profile
          flutter build apk --release
